#!/usr/bin/env sh

echo "$1" | grep "\.ar\." && {
  devour alacritty \
    --config-file ~/.config/alacritty/alacritty_ar.yml \
    -e "$EDITOR" "$1" &
  exit
}

case $(file --mime-type "$1" -bL) in

  text/* | inode/x-empty | application/json | application/octet-stream)
    "$EDITOR" "$1"
    ;;

  video/*)
    pidof mpv || devour mpv "$1"
    ;;

  application/pdf | application/postscript)
    pidof zathura || devour zathura "$1"
    ;;

  image/gif)
    pgrep mpv || devour "mpv --loop" "$1"
    ;;

  image/*)
    pidof feh ||
      devour \
        "feh -A 'set-bg %f' -B 'black' -F -d --edit --keep-zoom-vp --start-at" "$1"
    ;;

esac
